### ISSUE TITLE
Router does not consider context-path

### ISSUE THREAD

**Issue by benwiz** [life-research/blaze#59]
Router does not consider the configured `context-path` configured in [blaze.edn](https://github.com/life-research/blaze/blob/modular/blaze.edn#L36)

**Comment by alexanderkiel** [comment]
Please be patient, its still work in progress.

**Comment by alexanderkiel** [comment]
I merged #61. I have not tested other context paths then `/fhir` but would like to see new issues after I document the module system properly. Currently `blaze.edn` is not public.
