### ISSUE TITLE
Add URI encoder to Cheshire JSON response generator

### ISSUE THREAD

**Issue by benwiz** [life-research/blaze#84]
The following must be added to give Cheshire the ability to encode a `java.net.URI` as a string for json. I was not sure where you would want this to go so I've created an issue instead of PR.

No other changes should be needed.

```clj
(cheshire.generate/add-encoder java.net.URI cheshire.generate/encode-str)
```

**Comment by alexanderkiel** [comment]
Were do you have `java.net.URI`? I don't see it in the existing code.
